## Application configuration file Aurora CLI 2.0
## Version: 0.0.1

## Path to sign keys
## name - The name you will see in the list
## key  - Path to the key.pem file
## cert - Path to the cert.pem file
keys:
  - name: Regular
    key: /home/keygenqt/sign/dev/regular/developer-regular-key.pem
    cert: /home/keygenqt/sign/dev/regular/developer-regular-cert.pem
  - name: Regular2
    key: /home/keygenqt/sign/dev/regular/developer-regular-key.pem
    cert: /home/keygenqt/sign/dev/regular/developer-regular-cert.pem

## Devices list
## ip   - Device IP WI-FI or cable connection
## pass - SSH password
## port - SSH port
devices:
  - ip: 192.168.2.15
    devel-su: '00000'
    pass: '00000'
    port: 22
  - ip: 192.168.1.20
    devel-su: '00000'
    pass: '00000'
    port: 22
